### ISSUE TITLE
Fix Pojo Generator issue with Bytes

### ISSUE THREAD

**Issue by SirWellington** [SirWellington/alchemy-generator#14]
This exception keeps popping up on Classes with a Byte field:

```java
java.lang.NoSuchMethodException: java.lang.Byte.<init>()
	at java.lang.Class.getConstructor0(Class.java:3082) ~[na:1.8.0_66]
	at java.lang.Class.getDeclaredConstructor(Class.java:2178) ~[na:1.8.0_66]
	at tech.sirwellington.alchemy.generator.ObjectGenerators.instantiate(ObjectGenerators.java:216) [alchemy-generator-1.4-SNAPSHOT.jar:na]
	at tech.sirwellington.alchemy.generator.ObjectGenerators.canInstantiate(ObjectGenerators.java:192) [alchemy-generator-1.4-SNAPSHOT.jar:na]
	at tech.sirwellington.alchemy.generator.ObjectGenerators.pojos(ObjectGenerators.java:153) [alchemy-generator-1.4-SNAPSHOT.jar:na]
	at tech.sirwellington.alchemy.generator.ObjectGenerators.pojos(ObjectGenerators.java:147) [alchemy-generator-1.4-SNAPSHOT.jar:na]
	at tech.sirwellington.alchemy.generator.ObjectGenerators.determineGeneratorFor(ObjectGenerators.java:333) [alchemy-generator-1.4-SNAPSHOT.jar:na]
	at tech.sirwellington.alchemy.generator.ObjectGenerators.injectField(ObjectGenerators.java:266) [alchemy-generator-1.4-SNAPSHOT.jar:na]
	at tech.sirwellington.alchemy.generator.ObjectGenerators.tryInjectField(ObjectGenerators.java:253) [alchemy-generator-1.4-SNAPSHOT.jar:na]
	at tech.sirwellington.alchemy.generator.ObjectGenerators.lambda$pojos$31(ObjectGenerators.java:180) [alchemy-generator-1.4-SNAPSHOT.jar:na]
```

**Comment by SirWellington** [comment]
This isn't really an issue Per-Se, just going to reduce the verbosity of the logs
